### ISSUE TITLE
dapp event dag misses logs when Geth goes down

### ISSUE THREAD

**Issue by d3centr** [dapfyi/dap#6]
## Bug
While Geth was briefly down, the thread 7 of event dag's block partitioner in epoch 508 batched blocks 15247000 - 15247999. The Factory PoolCreated event at block 15247971 towards the end of the range was missed in Uniswap pipeline. More significantly, the task was marked successful. See the Gantt chart screenshot showing abnormally short tasks, expecting to last around 50s. They all completed within the same span of 4 seconds (shortest successful task lasting 20s).

<img width="349" alt="0" src="https://user-images.githubusercontent.com/85571997/197267115-dff4f86a-7b58-45a4-a958-4bbe0d003385.png">

As Geth was going down, websocket threads were gracefully terminated. Web3 python client interpreted this signal as a successful and complete request.

Out of the seven tasks running while Geth went down, a single task failed with error:
```
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
The next 2 tasks to launch failed abruptly with:
```
dap.utils.EthClientNotFoundError: no running instance named 'dap-geth-mainnet' in subnet
```
Only failed tasks ran again after a default 5mn backoff.

## Impact
The first known swap of the missing pool propagated null values down the pipeline, triggering various errors. The human readable price of a swap cannot be determined without reference to the pool factory event, referencing ERC20 contracts where decimals are retrieved. This overhead should not be multiplied for each swap, which are also referencing exchanged tokens.

## Prevention

*generic solutions external to DaP are not discussed*

A web3 socket task scanning events should only be marked successful if the client EC2 instance is in a *Running* state at the time of completion (even if the instance is still up, state would switch to *Terminating* when going down). `dap.utils.describe_instance()` is specifically filtering a running client instance: calling it after a data retrieval should suffice to ensure that the client wasn't going down at the time of completion; `EthClientNotFoundError` is thrown otherwise.

- Snippet to add below `get_all_entries()` and `get_logs()` in *airflow/dags/dap/events/etl.py*:
```python
# fails when a client goes down gracefully and could have missed events
describe_instance(conf['eth_client'])
```

**Comment by dapfyi** [comment]
fixed by #7
